version: '3'
services:
  tic-tac-toe:
    build:
      context:  /home/abdullah-saeed/PC/Game/game_app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
